trigger:
- master  

pool:
  vmImage: 'Default'

steps:
- task: welcome22
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'  
    tags: 'htmlapp:$(Build.BuildId)'
    azureSubscription: '2acd7718-d4d8-40e6-a8b8-8232fa98a0da'
    azureContainerRegistry: 'aksdemo99'

- task: Docker@2
  displayName: 'aksdemo99.azurecr.io/welcome:v1'
  inputs:
    command: 'push'
    tags: 'htmlapp:$(Build.BuildId)'
    azureSubscription: '2acd7718-d4d8-40e6-a8b8-8232fa98a0da'
    azureContainerRegistry: 'aksdemo99'

- task: KubernetesManifest@0
  displayName: 'Deploy to AKS'
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'aks-demo1'
    manifests: 'welcome-deployment.yaml'  
    containers: 'htmlapp:$(Build.BuildId)'
