apiVersion: v1
kind: Service
metadata:
  name: welcome-service
spec:
  type: NodePort
  selector:
    app: welcome
  ports:
    - protocol: TCP
      port: 81   # Port on the service
      targetPort: 81   # Port on the pod
      nodePort: 30000   # Choose a port in the range 30000-32767
---
apiVersion: v1
kind: Service
metadata:
  name: welcome-service
spec:
  type: LoadBalancer
  selector:
    app: welcome
  ports:
    - protocol: TCP
      port: 81   # Port on the service
      targetPort: 81   # Port on the pod

